### ISSUE TITLE
Switching to preview mode scrolls to top of document

### ISSUE THREAD

**Issue by jubberwockey** [Arch-Storm/obsidian-indent-lines#3] opened 2021-05-27 14:12 UTC
Obsidian version 0.12.3

When I am pressing `ctrl+e` or press the preview button, the preview mode scrolls to the top of the document instead of the current position in edit mode.
However, this behavior is not consistent, and depends on the cursor position in edit mode. For some cursor positions, the preview mode scrolls to a random position of the document.

This only happens when entering preview mode from edit mode. On returning from preview mode to edit mode, the current position is remembered correctly.

EDIT: I did some digging and found that unexpected scrolling behavior in preview mode is related to `postition: relative` in the CSS, see e.g. [here](https://forum.obsidian.md/t/triggering-preview-mode-in-long-docs-causes-preview-to-scroll-to-top-of-document-in-certain-cases/13663/2). So this seems to be a more general issue, but maybe you can find a workaround, I really like your plugin!

**Comment by Arch-Storm** [comment] 2021-05-28 09:55
This seems to be the same general problem as in #1 
I tried looking into a workaround for `position: relative` but haven't found one.
I found that similar CSS snippets also show this problem.

Gonna mark this as a duplicate of Issue #1 and add this in there.

**Closed by Arch-Storm** 2021-05-28 09:55 UTC
